model: mlp

# 数据集
data_path: datasets/EMO-DB  # 数据集路径 wsy fix
# class_labels: ["angry", "fear", "happy", "neutral", "sad", "surprise"]  # 情感标签
# class_labels: ["positive", "negative", "neutral"]
class_labels: ["angry", "boredom", "disgust", "fear", "happy", "neutral", "sad"]

# 特征
feature_folder: features/7-category # 特征存储文件夹 wsy fix
feature_method: o  # 'o': opensmile, 'l': librosa  # 特征提取方式

# Opensmile 配置，只在 'feature_method: o' 时需要设置
opensmile_config: IS10_paraling  # Opensmile 标准特征集
opensmile_path: /home/wangshiyao/wangshiyao_space/exp3/opensmile  # Opensmile 安装路径 wsy fix

# checkpoints
checkpoint_path: checkpoints/  # checkpoint 存储路径
checkpoint_name: MLP_OPENSMILE_IS10  # checkpoint 文件名

# 模型参数
params: {
  alpha: 1.9,
  max_iter: 700
}
